/**
 * EASYSEARCH — PDF builder
 *
 * Uses jsPDF (free, MIT-licensed, loaded from a CDN) entirely in the
 * browser — no server, no per-document cost.
 *
 * Note on sourcing: content is drawn from Wikipedia, which is published
 * under CC BY-SA. We print a source/attribution line on the document as
 * required by that license — please keep this in any version you ship.
 */
const PdfBuilder = (() => {
  const MARGIN = 48;
  const PAGE_W = 595.28; // A4 pt
  const PAGE_H = 841.89;
  const MAX_W = PAGE_W - MARGIN * 2;
  const LINE_H = 15;

  function newDoc() {
    return new window.jspdf.jsPDF({ unit: "pt", format: "a4" });
  }

  function footer(doc, pageNum) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(140, 140, 140);
    doc.text("EASYSEARCH", MARGIN, PAGE_H - 24);
    doc.text(String(pageNum), PAGE_W - MARGIN, PAGE_H - 24, { align: "right" });
  }

  function build(data, meta) {
    const doc = newDoc();
    let y = MARGIN;
    let page = 1;

    function ensureSpace(h) {
      if (y + h > PAGE_H - MARGIN - 20) {
        footer(doc, page);
        doc.addPage();
        page++;
        y = MARGIN;
      }
    }

    function writeParagraph(text, size = 11, color = [40, 40, 40], gapAfter = 10) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(size);
      doc.setTextColor(...color);
      const lines = doc.splitTextToSize(text, MAX_W);
      lines.forEach(line => {
        ensureSpace(LINE_H);
        doc.text(line, MARGIN, y);
        y += LINE_H;
      });
      y += gapAfter;
    }

    function writeHeading(text, size = 15) {
      ensureSpace(size + 18);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(size);
      doc.setTextColor(20, 35, 60);
      doc.text(text, MARGIN, y);
      y += size + 6;
      doc.setDrawColor(200, 210, 225);
      doc.setLineWidth(0.75);
      doc.line(MARGIN, y - 10, PAGE_W - MARGIN, y - 10);
    }

    // ---- Title block ----
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(10, 20, 35);
    const titleLines = doc.splitTextToSize(data.title, MAX_W);
    titleLines.forEach(l => { doc.text(l, MARGIN, y); y += 26; });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    doc.setTextColor(110, 120, 140);
    const designationLabel = { school: "School", college: "College", job: "Job / Professional" }[meta.designation] || meta.designation;
    doc.text(`Prepared for: ${designationLabel}   ·   ${meta.dateStr}`, MARGIN, y);
    y += 26;

    // ---- Lead image (optional — skipped silently if none was found) ----
    if (data.image && data.image.dataUrl) {
      const naturalW = data.image.width || 640;
      const naturalH = data.image.height || 400;
      const maxH = 220;
      let w = MAX_W;
      let h = (naturalH / naturalW) * w;
      if (h > maxH) { h = maxH; w = (naturalW / naturalH) * h; }

      ensureSpace(h + 24);
      const format = data.image.dataUrl.includes("image/png") ? "PNG" : "JPEG";
      try {
        doc.addImage(data.image.dataUrl, format, MARGIN, y, w, h);
        y += h + 6;
        writeParagraph(`Image via Wikimedia Commons — see the source article for its specific license.`, 8, [150, 155, 168], 14);
      } catch (e) {
        console.warn("Could not embed image, continuing without it:", e);
      }
    }

    // ---- Sections ----
    data.sections.forEach(sec => {
      writeHeading(sec.heading);
      writeParagraph(sec.text);
    });

    // ---- Questions ----
    if (data.questions && data.questions.length) {
      ensureSpace(40);
      writeHeading("Practice Questions", 16);
      data.questions.forEach((qa, i) => {
        writeParagraph(`${i + 1}. ${qa.q}`, 11.5, [25, 30, 45], 4);
        writeParagraph(`Answer: ${qa.a}`, 10.5, [95, 105, 125], 12);
      });
    }

    // ---- Attribution (Wikipedia content is CC BY-SA — attribution required) ----
    ensureSpace(60);
    doc.setDrawColor(210, 215, 225);
    doc.line(MARGIN, y, PAGE_W - MARGIN, y);
    y += 16;
    writeParagraph(
      `Source material adapted from the Wikipedia article "${data.sourceTitle}", available under the Creative Commons Attribution-ShareAlike License. Content has been restructured and shortened for study purposes.`,
      8.5, [140, 145, 160], 6
    );
    writeParagraph(`Generated by EasySearch. Developed by ${CONFIG.DEVELOPER}.`, 8.5, [140, 145, 160], 0);

    footer(doc, page);
    return doc;
  }

  /** Builds and triggers a browser download. Returns the filename used. */
  function buildAndDownload(data, meta) {
    const doc = build(data, meta);
    const safeName = data.title.replace(/[^a-z0-9]+/gi, "_").slice(0, 60);
    const filename = `${safeName}_${meta.designation}.pdf`;
    doc.save(filename);
    return filename;
  }

  return { build, buildAndDownload };
})();
